# Test
language: python

sudo: false

python:
  - "2.7"

script:
- pebble-dev/${PEBBLE_SDK}/bin/pebble build

before_install:
  - wget https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.2.1-linux64.tar.bz2
  - mkdir -p pebble-dev
  - tar -jxf pebble-sdk-* -C pebble-dev
  - touch pebble-dev/NO_TRACKING
  - export PEBBLE_SDK=pebble-dev/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble

# notice we don't create a virtualenv, travis to that be default already
install:
- pip install --upgrade pip # just to future proof, since travis seem to hang behind
- pip install --install-option="--no-cython-compile" cython
- "pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt"

env:
  global:
  - PEBBLE_SDK=PebbleSDK-3.12
