sudo: false

language: python
python:
 - 2.7

addons:
  apt:
    sources:
      - libsdl1.2debian
      - libfdt1
      - libpixman-1-0

before_install:
 - pip install virtualenv

install:
 - mkdir pebble-dev
 - cd pebble-dev
 - curl -O https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-$PEBBLE_TOOL-linux64.tar.bz2
 - tar -jxf pebble-sdk-$PEBBLE_TOOL-linux64.tar.bz2
 - cd pebble-sdk-$PEBBLE_TOOL-linux64
 - virtualenv --no-site-packages .env
 - source .env/bin/activate
 - pip install -r requirements.txt
 - pip install cpplint

script:
 - bin/pebble build
 - source .env/bin/activate
 - cpplint src/*

env:
  global:
    - PEBBLE_TOOL=4.2

branches:
  only:
    - master
